# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
