# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_access_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='OTP',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
